apiVersion: v1
kind: PersistentVolume
metadata:
  name: datasets-pv
  labels:
    type: local
    volume: test-datasets
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/openuba/root/test_datasets"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-pvc
  namespace: openuba
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: test-datasets
