apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-storage-pv
  labels:
    type: local
    volume: model-storage
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/openuba/root/core/model_library"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-storage-pv
  labels:
    type: local
    volume: system-storage
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/openuba/root/.openuba"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-storage-pvc
  namespace: openuba
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: system-storage
