apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-source-pv
  labels:
    type: local
    volume: frontend-source
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/openuba/root/interface"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-source-pvc
  namespace: openuba
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: frontend-source
