apiVersion: v1
kind: PersistentVolume
metadata:
  name: metastore-pv
  labels:
    type: local
    volume: metastore
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/openuba/root/metastore"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metastore-pvc
  namespace: openuba
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: metastore
