apiVersion: v1
kind: PersistentVolume
metadata:
  name: saved-models-pv
  labels:
    type: local
    volume: saved-models
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/openuba/root/core/storage/saved_models"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saved-models-pvc
  namespace: openuba
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: saved-models
