apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: openuba
type: Opaque
stringData:
  password: gacwr
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: openuba
type: Opaque
stringData:
  database-url: postgresql://gacwr:gacwr@postgres:5432/openuba

